hw5
HalamBalam/js-homeworks pull request #6
Opened 2022-07-06 22:51 UTC by HalamBalam

2022-07-07 10:37 UTC, fanisco requested changes

2022-07-07 10:37 UTC, fanisco commented on hw5/chess.js
> +        this.cell = undefined;
Наверное фигура не должна знать о своем положении на доске

2022-07-07 10:37 UTC, fanisco commented on hw5/chess.js
> +        this.currentClass = Pawn;
Достаточно странная реализация. Я бы создал метод, который заменяет экземпляр одного класса на экземпляр другого.

2022-07-07 10:37 UTC, fanisco commented on hw5/chess.js
> +        this.winner = undefined;
Я бы заменил это поле статусом, как требуется по заданию:
```
Состояние игры: победа белого, победа черного, игра продолжается
```

2022-07-07 17:38 UTC, HalamBalam commented on hw5/chess.js
> +        this.cells[row][col] = figure;
Она попадет в lostFigures класса Game. Это предусмотрено в методе move.

2022-07-08 07:17 UTC, fanisco approved these changes

2022-07-10 19:01 UTC, merged